version: "3"
services:
  nginx-proxy:
    image: nginx
    container_name: nginx
    privileged: true
    restart: always
    ports:
      - "8001:8001"
      - "4434:4434"
    volumes:
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/nginx/cert:/etc/nginx
      - /home/nginx/logs:/usr/local/nginx/logs

